version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: Jellyfin
    restart: unless-stopped

    ports:
      - "8097:8096"

    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/Media

    environment:
      - TZ=America/Sao_Paulo
